### ISSUE TITLE
Specify in README that the project needs lwjgl3ify 1.5.7+

### ISSUE THREAD

**Issue by JL2210** [makamys/OptiFine3ify#1]
I loaded this mod under lwjgl3ify 1.5.1 (GT 2.4.1 packaged version) and the world did not render around spawn and flashed violently everywhere else. When using lwjgl3ify 1.5.7 the world loaded normally and had no missing chunks. Might be a good idea to put that in the README in case anyone else wants to use this mod.

**Comment by makamys** [comment]
> flashed violently 

If you had FastCraft then this is expected. Lwjgl3ify's STB stitching tweak (`stbiTextureStiching`) is incompatible with FastCraft, which is why it's supposed to get disabled automatically if it's detected. But the detection logic wasn't correct for FastCraft 1.23 until lwjgl3ify 1.5.7, requiring it to be disabled manually. If you did that then any old lwjgl3ify version should work. I will add that to the README.
